spring.application.name: resource-service-resttemplate
server.port: 8082
debug: true

eureka.client.service-url:
  defaultZone: http://localhost:8761/eureka/
spring.cloud:
  discovery:
    client:
      health-indicator:
        enabled: true
        include-description: true
#spring.zipkin.base-url: http://192.168.99.100:9411/
#spring.sleuth.sampler.probability: 1

security:
  oauth2:
    client:
      client-id: client_2
      client-secret: 123456
      user-info-url: http://localhost:8081/api/userInfo
      auth-code:
        enabled: true
        access-token-url: http://localhost:8080/uaa/oauth/token
        authorize-url: http://localhost:8080/uaa/oauth/authorize
        redirect-url: http://localhost:8082/callback
        scope: read
          
        
